In [1]:
print("hi")

hi


In [2]:
import numpy as np

In [ ]:
np.arange(10)

In [ ]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the surfaceArea function below.
def surfaceArea(A):
    print(A)
if __name__ == '__main__':

    HW = input().split()

    H = int(HW[0])

    W = int(HW[1])

    A = []

    for _ in range(H):
        A.append(list(map(int, input().rstrip().split())))
    
    result = surfaceArea(A)



In [9]:
A

[[1, 3], [2, 1]]

In [11]:
T=np.asarray(A)

In [60]:
T

array([[1, 3],
       [2, 1]])

In [14]:
T[0,0]

1

In [15]:
x=[0,0]

In [18]:
i=0;
j=1;
T[i,j]

3

In [39]:
i=0
while i<2:
    j=0
    while j<2:
        print("Cell and wt at analysis -",i,j,"-",T[i,j])
        if(j+1<2):
            print('E',i,j+1)
        if(j-1>-1):
            print('W',i,j-1)
        if(i-1>-1):
            print('N',i-1,j)
        if(i+1<2):
            print('S',i+1,j)
        j=j+1
    i=i+1

Cell and wt at analysis - 0 0 - 1
E 0 1
S 1 0
Cell and wt at analysis - 0 1 - 3
W 0 0
S 1 1
Cell and wt at analysis - 1 0 - 2
E 1 1
N 0 0
Cell and wt at analysis - 1 1 - 1
W 1 0
N 0 1


In [20]:
T[-1,0]

2

In [86]:
def wtCal():
    sc=0;
    row=2
    col=2
    i=0
    while i<row:
        j=0
        while j<col:
            if(T[i,j]>0):
                print("Cell and wt at analysis -",i,j,"-",T[i,j])
                if(j+1<row):
                    print('E',i,j+1)
                    print('with wt-',T[i,j+1])
                    if(T[i,j+1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                if(j-1>=0):
                    print('W',i,j-1)
                    print('with wt-',T[i,j-1])
                    if(T[i,j-1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i-1>=0):
                    print('N',i-1,j)
                    print('with wt-',T[i-1,j])
                    if(T[i-1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i+1<row):
                    print('S',i+1,j)
                    print('with wt-',T[i+1,j])
                    if(T[i+1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(T[i,j]==1):
                    print('T',i,j)
                    sc=sc+1;
            j=j+1
        i=i+1
        print(sc)

In [87]:
wtCal()

Cell and wt at analysis - 0 1 - 1
W 0 0
with wt- -1
S 1 1
with wt- -1
T 0 1
5
5


In [83]:
T=T-1

In [81]:
def wtReducer():
    T=T-1

In [65]:
for i in T:
    for j in i:
        if(j<=0):
            continue
        print(j)

2
1


In [63]:
wtReducer()

UnboundLocalError: local variable 'T' referenced before assignment

In [85]:
T

array([[-1,  1],
       [ 0, -1]])

In [171]:
#!/bin/python3

import math
import os
import random
import re
import sys

#for a specific level check if for a cell blocks exists around it if no block exists then add up the sc(surface count)
def wtCal():
    sc=0;
    row=H
    col=W
    i=0
    while i<row:
        j=0
        while j<col:
            if(T[i,j]>0):
                #print("Cell and wt at analysis -",i,j,"-",T[i,j])
                if(j+1<row):
                    #print('E',i,j+1)
                   # print('with wt-',T[i,j+1])
                    if(T[i,j+1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                if(j-1>=0):
                   #print('W',i,j-1)
                    #print('with wt-',T[i,j-1])
                    if(T[i,j-1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i-1>=0):
                   # print('N',i-1,j)
                    #print('with wt-',T[i-1,j])
                    if(T[i-1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i+1<row):
                   #print('S',i+1,j)
                   # print('with wt-',T[i+1,j])
                    if(T[i+1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(T[i,j]==1):
                    #print('T',i,j)
                    sc=sc+1;
            j=j+1
        i=i+1
    return sc


# Complete the surfaceArea function below.
def surfaceArea(T):
    i=0
    res=0
    while(i<np.max(T)):
        res=res+wtCal()
        T=T-1
        baseSurface=H*W
    return(res+baseSurface)

if __name__ == '__main__':

    HW = input().split()

    H = int(HW[0])

    W = int(HW[1])

    A = []

    for _ in range(H):
        A.append(list(map(int, input().rstrip().split())))
    T=np.asarray(A)
    result = surfaceArea(T)

print(result)

3 3
1 2 3
2 2 3
1 2 1
54


In [160]:
A

[[4, 2, 1], [2, 3, 1], [2, 2, 3]]

NameError: name 'dim' is not defined

In [170]:
#for a specific level check if for a cell blocks exists around it if no block exists then add up the sc(surface count)
def wtCal():
    sc=0;
    row=H
    col=W
    i=0
    while i<row:
        j=0
        while j<col:
            if(T[i,j]>0):
                #print("Cell and wt at analysis -",i,j,"-",T[i,j])
                if(j+1<row):
                    #print('E',i,j+1)
                   # print('with wt-',T[i,j+1])
                    if(T[i,j+1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                if(j-1>=0):
                   #print('W',i,j-1)
                    #print('with wt-',T[i,j-1])
                    if(T[i,j-1]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i-1>=0):
                   # print('N',i-1,j)
                    #print('with wt-',T[i-1,j])
                    if(T[i-1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(i+1<row):
                   #print('S',i+1,j)
                   # print('with wt-',T[i+1,j])
                    if(T[i+1,j]<=0):
                        sc=sc+1
                else:
                    sc=sc+1 
                    
                if(T[i,j]==1):
                    #print('T',i,j)
                    sc=sc+1;
            j=j+1
        i=i+1
    return sc


In [141]:
#reduce wt 1 by 1
T=T+4
T

array([[1, 3, 4],
       [2, 2, 3],
       [1, 2, 4]])

In [169]:
T

array([[-1641677, -1641679, -1641680],
       [-1641679, -1641678, -1641680],
       [-1641679, -1641679, -1641678]])

In [166]:
max(max(A))

4

In [168]:
i=0
res=0
while(i<max(max(A))):
    res=res+wtCal()
    T=T-1
    i=i+1
baseSurface=H*W
print(res+baseSurface)

9


In [134]:
T=T+4

In [151]:
a=np.asarray('')

In [152]:
a

array('', dtype='<U1')

In [153]:
a=np.asarray(A)

In [154]:
a

array([[1, 3, 4],
       [2, 2, 3],
       [1, 2, 4]])

In [1]:
L=[[2,3],[1,2]]

In [2]:
type(L)

list

In [3]:
array(L)

NameError: name 'array' is not defined

In [5]:
A=array('e')

NameError: name 'array' is not defined

In [6]:
import array as arr

In [1]:
L=[[2,3],[1,2]]

In [4]:
L=[[2,3],[1,2]]

In [8]:
dataset_list = ''.join(input_list)
dataset_array = []
for item in dataset_list.split(';'): # comma, or other
    dataset_array.append(item)

AttributeError: 'list' object has no attribute 'split'

In [7]:
dataset_list = ''.join(L)

TypeError: sequence item 0: expected str instance, list found

In [11]:
dataset_list=''.join(str(e) for e in L)

In [17]:
L=[[2,3],[1,2]]

In [20]:
dataset_list=','.join(str(e) for e in L)
dataset_array = []
for item in dataset_list.split(','): # comma, or other
    dataset_array.append(item)

In [21]:
dataset_array

['[2', ' 3]', '[1', ' 2]']

In [22]:
L

[[2, 3], [1, 2]]

In [36]:
import array as arr
A=arr.array('i',[[0,2,3],[8,9,7]])

TypeError: an integer is required (got type list)

In [34]:
type(A)

array.array

In [40]:
B=arr.array('i')

In [37]:
L[1][1]

2

In [42]:
B[0]=1

IndexError: array assignment index out of range

In [43]:
a=[2,4,5,5]

In [46]:
a.reshape(2,2)

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
A=[2,3,4,5,9,6]

In [47]:
[a.reshape(2,3) for a in A]

AttributeError: 'int' object has no attribute 'reshape'

In [57]:
b=arr.array('i')
b = [[ 0 for y in range( 2 )] 
             for x in range( 2 )] 

In [58]:
b

[[0, 0], [0, 0]]

In [59]:
type(b)

list

In [60]:
d={}
type(b)

list

In [63]:
d[1,2]=5

In [64]:
type(d)

dict

In [65]:
d

{(1, 2): 5}

In [70]:
b=arr.array('i')

In [71]:
type(b)

array.array

In [72]:
b.append([])

TypeError: an integer is required (got type list)

In [73]:
b = [[0]*5 for i in range(5)]

In [74]:
type(b)

list

In [79]:
def zeros_matrix(rows, cols):
    """
    Creates a matrix filled with zeros.
        :param rows: the number of rows the matrix should have
        :param cols: the number of columns the matrix should have
 
        :return: list of lists that form the matrix
    """
    M = arr.array('i')
    while len(M) < rows:
        M.append([])
        while len(M[-1]) < cols:
            M[-1].append(0.0)
 
    return M

In [80]:
m=zeros_matrix(2,2)

TypeError: an integer is required (got type list)

In [77]:
m

[[0.0, 0.0], [0.0, 0.0]]

In [78]:
type(m)

list

In [83]:
import random
x=[[random.random() for _ in range(3)] for _ in range(7)]

In [85]:
type(x)

list

In [86]:
import os

In [87]:
os.getcwd()

'C:\\Users\\697641'

In [89]:
os.chdir('C:\\Users\\697641\\Python_Projects')